import { nunito_sans } from "@/utils/font";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito_sans}>
        <div className="flex flex-col md:flex-row">
          <Sidebar />
          <div className="flex-1 px-4 md:px-6 min-h-screen bg-gradient-to-tr from-color-bgPrime to-color-bgSecond">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
