import { nunito_sans } from "@/utils/font";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito_sans}>
        <div className="flex flex-col md:flex-row">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
